language: C
dist: "trusty"
branches:
  only:
  - /autobuild-.*/
env:
  global:
  - yara_version=1.7
  - geoip_version=1.6.9
  - pcap_version=1.8.1
  - curl_version=7.52.1
  - glib2_dir="2.50"
  - glib2_version=2.50.2
  - node_version=4.6.2
  - daq_version=2.0.6
  - lua_version=5.3.3
  - moloch_name= moloch
  - fpm_url="https://github.com/jpvlsmv/moloch"
  - fpm_description= "Moloch Full Packet System"
  - iteration= 1
addons:
  apt:
    packages:
    -  wget 
    -  curl 
    -  libpcre3-dev 
    -  uuid-dev 
    -  libmagic-dev 
    -  pkg-config 
    -  g++ 
    -  flex 
    -  bison 
    -  zlib1g-dev 
    -  libffi-dev 
    -  gettext 
    -  libgeoip-dev 
    -  make 
    -  libjson-perl 
    -  libbz2-dev 
    -  libwww-perl 
    -  libpng-dev 
    -  xz-utils 
    -  libffi-dev 
    -  libssl-dev
    -  liblua5.2-dev
    -  libdaq-dev
before_script:
- gem install fpm
- ./easybutton-build.sh
cache:
  directories:
  - thirdparty
before_cache:
  - cp /dev/null $HOME/build/jpvlsmv/moloch/thirdparty/libpcap-1.7.4/config.log
script:
  - make
