language: C
dist: "trusty"
branches:
  only:
  - /autobuild-.*/
addons:
  apt:
    packages:
    -  wget 
    -  curl 
    -  libpcre3-dev 
    -  uuid-dev 
    -  libmagic-dev 
    -  pkg-config 
    -  g++ 
    -  flex 
    -  bison 
    -  zlib1g-dev 
    -  libffi-dev 
    -  gettext 
    -  libgeoip-dev 
    -  make 
    -  libjson-perl 
    -  libbz2-dev 
    -  libwww-perl 
    -  libpng-dev 
    -  xz-utils 
    -  libffi-dev 
    -  libssl-dev
before_script:
- ./easybutton-build.sh -p
cache:
  directories:
  - thirdparty
script: true
