shared:
    settings:
        email:
            addresses: [moloch.build@oath.com]
            statuses: [SUCCESS, FAILURE]
jobs:
    main:
        image: andywick/moloch-build-7:6
        steps:
            - ln -s /thirdparty .
            - build: ./easybutton-build.sh
            - export PATH=/data/moloch/bin:$PATH
            - installing: make install
            - cp -r capture/plugins/lua/samples /data/moloch/lua
            - test-capture: (cd tests ; ./tests.pl)
            - export TZ=US/Eastern
            - test-ui: (cd viewer; npm install ; npm test)
            - wise-npm: (cd capture/plugins/wiseService; npm install)
            - build-package: |
                export MOLOCH_VERSION=`sed 's/.*"\(.*\)\".*$/\1/' /data/moloch/viewer/version.js | tr "-" "_"`
                if [ "$GIT_BRANCH" = "origin/master" ]; then
                  fpm -s dir -t rpm -n moloch -v $MOLOCH_VERSION --iteration $SD_BUILD_ID /data/moloch
                  aws s3 cp --quiet moloch*.x86_64.rpm s3://files.molo.ch/moloch-master.x86_64.rpm --acl public-read
                  aws s3api put-object-acl --bucket files.molo.ch --key moloch-master.x86_64.rpm --acl public-read
                fi
            - slack-success: |
                BUILD_VERSION=`git describe --tags`
                MSG=`git log -1 --format=%s`
                BODY="{\"icon_emoji\": \":sushi:\", \"username\": \"MolochBuild\", \"text\":\"It worked: $GIT_BRANCH - moloch-$MOLOCH_VERSION-$SD_BUILD_ID - $MSG\"}"
                ls -l moloch*
                curl -XPOST -H "Content-type: application/json" --data "$BODY" $SLACK
        secrets:
            - SLACK
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY

